### ISSUE TITLE
请问能降低下ms store里写的配置要求吗

### ISSUE THREAD

**Issue by YixinZhang2002** [EveElseIf/BilibiliDownloadToolUWP#1]
虽然知道是开玩笑的,而且之前能无视条件下载;
但win11beta最新版商店貌似突然不让下载了,( 如图,install为灰色,库里也下载不了)
MS Store Version 22108.1401.11.0 ,Windows 11 Build 22000.184
麻了.希望帮解决一下
![Screenshot 2021-09-13 182510](https://user-images.githubusercontent.com/73466559/133068236-369c9773-a87d-4c62-964e-b2c8f165e32e.png)
![Screenshot 2021-09-13 183418](https://user-images.githubusercontent.com/73466559/133069181-a708eaca-0c34-4bec-aaf7-4019de735417.png)

**Comment by EveElseIf** [comment]
最近开学太忙了，等我有空可能就会改一改

**Comment by EveElseIf** [comment]
已经调整好了
